# Generated by Django 5.1.7 on 2025-03-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is_completed')),
            ],
        ),
    ]
